server:
  port: 8082
spring:
  application:
    name: drone-app
  datasource:
    url: jdbc:h2:mem:drone
    driver-class-name: org.h2.Driver
    username: musalasoft
    password: musalasoft
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
scheduler:
  interval: 6000

logging:
  file:
    name: logs/drone_capacity.log

