server:
  port: 8082
spring:
  application:
    name: drone-app
  datasource:
    url: jdbc:h2:mem:drone
    driver-class-name: org.h2.Driver
    username: musalasoft
    password: musalasoft
  #    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#  liquibase:
#    enabled: false
#    change-log: classpath:/db/changelog/db.changelog-master.yml
#        default_schema: drones
#    database-change-log-lock-table: drones_databasechangeloglock
#    database-change-log-table: drones_databasechangelog
scheduler:
  interval: 6000

logging:
  file:
    name: logs/drone_capacity.log

